/** Admin Competition Photo Details — Figma 339:1796 / 339:1936 / 339:2155 / 339:2375. */

const A = '/assets/admin-competition-detail';
const HOME = '/assets/home';
const CD = '/assets/competition-details';

export const ADMIN_DETAIL_ASSETS = {
  divider: `${A}/divider.svg`,
  photographer: `${A}/photographer.jpg`,
  curves: {
    red: `${A}/curve-red.svg`,
    blue: `${A}/curve-blue.svg`,
    twelve: `${A}/curve-12.svg`,
  },
};

const RED_SIGNS = [
  {
    id: 'aries',
    number: 1,
    nameKey: 'adminCompetitionDetail.signs.aries',
    icon: `${HOME}/icon-aries.svg`,
    thumb: `${A}/thumb-1.jpg`,
    hero: `${A}/hero-six-red.jpg`,
    theme: 'red',
  },
  {
    id: 'taurus',
    number: 2,
    nameKey: 'adminCompetitionDetail.signs.taurus',
    icon: `${HOME}/icon-taurus.svg`,
    thumb: `${A}/thumb-2.jpg`,
    hero: `${A}/thumb-2.jpg`,
    theme: 'red',
  },
  {
    id: 'gemini',
    number: 3,
    nameKey: 'adminCompetitionDetail.signs.gemini',
    icon: `${HOME}/icon-gemini.svg`,
    thumb: `${A}/thumb-3.jpg`,
    hero: `${A}/thumb-3.jpg`,
    theme: 'red',
  },
  {
    id: 'cancer',
    number: 4,
    nameKey: 'adminCompetitionDetail.signs.cancer',
    icon: `${HOME}/icon-cancer.svg`,
    thumb: `${A}/thumb-4.jpg`,
    hero: `${A}/thumb-4.jpg`,
    theme: 'red',
  },
  {
    id: 'leo',
    number: 5,
    nameKey: 'adminCompetitionDetail.signs.leo',
    icon: `${HOME}/icon-leo.svg`,
    thumb: `${A}/thumb-5.jpg`,
    hero: `${A}/thumb-5.jpg`,
    theme: 'red',
  },
  {
    id: 'virgo',
    number: 6,
    nameKey: 'adminCompetitionDetail.signs.virgo',
    icon: `${HOME}/icon-virgo.svg`,
    thumb: `${CD}/thumb-6.jpg`,
    hero: `${CD}/thumb-6.jpg`,
    theme: 'red',
  },
];

const BLUE_SIGNS = [
  {
    id: 'libra',
    number: 7,
    nameKey: 'adminCompetitionDetail.signs.libra',
    icon: `${HOME}/icon-libra.svg`,
    thumb: `${A}/blue-thumb-1.jpg`,
    hero: `${A}/hero-six-blue.jpg`,
    theme: 'blue',
    iconBoxed: true,
  },
  {
    id: 'scorpio',
    number: 8,
    nameKey: 'adminCompetitionDetail.signs.scorpio',
    icon: `${HOME}/icon-scorpio.svg`,
    thumb: `${A}/blue-thumb-2.jpg`,
    hero: `${A}/blue-thumb-2.jpg`,
    theme: 'blue',
    iconBoxed: true,
  },
  {
    id: 'sagittarius',
    number: 9,
    nameKey: 'adminCompetitionDetail.signs.sagittarius',
    icon: `${HOME}/icon-sagittarius.svg`,
    thumb: `${A}/blue-thumb-3.jpg`,
    hero: `${A}/blue-thumb-3.jpg`,
    theme: 'blue',
  },
  {
    id: 'capricorn',
    number: 10,
    nameKey: 'adminCompetitionDetail.signs.capricorn',
    icon: `${HOME}/icon-capricorn.svg`,
    thumb: `${A}/blue-thumb-4.jpg`,
    hero: `${A}/blue-thumb-4.jpg`,
    theme: 'blue',
  },
  {
    id: 'aquarius',
    number: 11,
    nameKey: 'adminCompetitionDetail.signs.aquarius',
    icon: `${HOME}/icon-aquarius.svg`,
    thumb: `${A}/blue-thumb-5.jpg`,
    hero: `${A}/blue-thumb-5.jpg`,
    theme: 'blue',
    iconBoxed: true,
  },
  {
    id: 'pisces',
    number: 12,
    nameKey: 'adminCompetitionDetail.signs.pisces',
    icon: `${HOME}/icon-pisces.svg`,
    thumb: `${A}/blue-thumb-6.jpg`,
    hero: `${A}/blue-thumb-6.jpg`,
    theme: 'blue',
  },
];

const SHARED_COPY = {
  descriptionKey: 'adminCompetitionDetail.description',
  votes: '2150',
  views: '12400',
  photographerKey: 'adminCompetitionDetail.photographerName',
  photographerAvatar: ADMIN_DETAIL_ASSETS.photographer,
  categoryKey: 'adminCompetitionDetail.categories.nature',
};

/** Map showcase card id → admin photo detail variant. */
export const ADMIN_COMPETITION_DETAILS = {
  wings: {
    id: 'wings',
    variant: 'single',
    typeKey: 'adminCompetitions.types.single',
    titleKey: 'adminCompetitionDetail.entries.wings.title',
    hero: `${A}/hero-single.jpg`,
    sign: RED_SIGNS[0],
    slides: [],
    curve: null,
    ...SHARED_COPY,
  },
  forest: {
    id: 'forest',
    variant: 'single',
    typeKey: 'adminCompetitions.types.single',
    titleKey: 'adminCompetitionDetail.entries.forest.title',
    hero: `${A}/hero-single.jpg`,
    sign: RED_SIGNS[0],
    slides: [],
    curve: null,
    ...SHARED_COPY,
  },
  morning: {
    id: 'morning',
    variant: 'single',
    typeKey: 'adminCompetitions.types.single',
    titleKey: 'adminCompetitionDetail.entries.morning.title',
    hero: `${A}/hero-single.jpg`,
    sign: RED_SIGNS[0],
    slides: [],
    curve: null,
    ...SHARED_COPY,
  },
  harbor: {
    id: 'harbor',
    variant: 'single',
    typeKey: 'adminCompetitions.types.single',
    titleKey: 'adminCompetitionDetail.entries.harbor.title',
    hero: `${A}/hero-single.jpg`,
    sign: RED_SIGNS[0],
    slides: [],
    curve: null,
    ...SHARED_COPY,
  },
  silent: {
    id: 'silent',
    variant: 'single',
    typeKey: 'adminCompetitions.types.single',
    titleKey: 'adminCompetitionDetail.entries.silent.title',
    hero: `${A}/hero-single.jpg`,
    sign: RED_SIGNS[0],
    slides: [],
    curve: null,
    ...SHARED_COPY,
  },
  autumn: {
    id: 'autumn',
    variant: 'six-red',
    typeKey: 'adminCompetitions.types.six',
    titleKey: 'adminCompetitionDetail.entries.autumn.title',
    hero: null,
    sign: null,
    slides: RED_SIGNS,
    curve: ADMIN_DETAIL_ASSETS.curves.red,
    ...SHARED_COPY,
    votes: '1488',
    views: '9240',
    photographerKey: 'adminCompetitionDetail.photographerKasia',
  },
  city: {
    id: 'city',
    variant: 'six-blue',
    typeKey: 'adminCompetitions.types.six',
    titleKey: 'adminCompetitionDetail.entries.city.title',
    hero: null,
    sign: null,
    slides: BLUE_SIGNS,
    curve: ADMIN_DETAIL_ASSETS.curves.blue,
    ...SHARED_COPY,
  },
  zodiac: {
    id: 'zodiac',
    variant: 'twelve',
    typeKey: 'adminCompetitions.types.zodiac',
    titleKey: 'adminCompetitionDetail.entries.zodiac.title',
    hero: null,
    sign: null,
    slides: [...RED_SIGNS, ...BLUE_SIGNS],
    curve: ADMIN_DETAIL_ASSETS.curves.twelve,
    ...SHARED_COPY,
  },
};

export const getAdminCompetitionDetailById = (id) =>
  ADMIN_COMPETITION_DETAILS[id] || ADMIN_COMPETITION_DETAILS.wings;
