/** Prize & Payments — Figma node 111:1793. */
const A = '/assets/prize-payments';

export const PRIZE_PAYMENTS_ASSETS = {
  requestPayout: `${A}/request-payout.svg`,
  wallet: `${A}/wallet.svg`,
  earned: `${A}/earned.svg`,
  pendingClock: `${A}/pending-clock.svg`,
  txnTrophy1: `${A}/txn-trophy-1.svg`,
  txnTrophy2: `${A}/txn-trophy-2.svg`,
  txnCard: `${A}/txn-card.svg`,
  txnTrophy3: `${A}/txn-trophy-3.svg`,
  txnPending: `${A}/txn-pending.svg`,
};

export const SUMMARY_CARDS = [
  {
    id: 'wallet',
    labelKey: 'prizePayments.summary.wallet',
    valueKey: 'prizePayments.summary.walletValue',
    icon: PRIZE_PAYMENTS_ASSETS.wallet,
    iconWidth: 20,
    iconHeight: 16,
    iconBg: 'bg-[#e9ddff]',
    valueClass: 'text-[#532aa8]',
    orbClass: 'bg-[rgba(83,42,168,0.05)]',
  },
  {
    id: 'earned',
    labelKey: 'prizePayments.summary.earned',
    valueKey: 'prizePayments.summary.earnedValue',
    icon: PRIZE_PAYMENTS_ASSETS.earned,
    iconWidth: 22,
    iconHeight: 16,
    iconBg: 'bg-[#ffddb8]',
    valueClass: 'text-[#161c27]',
    orbClass: 'bg-[rgba(133,83,0,0.05)]',
  },
  {
    id: 'pending',
    labelKey: 'prizePayments.summary.pending',
    valueKey: 'prizePayments.summary.pendingValue',
    icon: PRIZE_PAYMENTS_ASSETS.pendingClock,
    iconWidth: 20,
    iconHeight: 20,
    iconBg: 'bg-[#dde2f3]',
    valueClass: 'text-[#7a7484]',
    orbClass: 'bg-[rgba(70,71,68,0.05)]',
  },
];

export const PRIZING_ROWS = [
  { id: 'p1', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.first', votes: '12,408', prize: '$2000' },
  { id: 'p2', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.second', votes: '80,000', prize: '$4000' },
  { id: 'p3', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.first', votes: '4,000', prize: '$8000' },
  { id: 'p4', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.third', votes: '13,805', prize: '$7000' },
  { id: 'p5', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.first', votes: '20,589', prize: '$8000' },
  { id: 'p6', nameKey: 'prizePayments.prizing.items.celestial', positionKey: 'prizePayments.prizing.positions.second', votes: '56,800', prize: '$7000' },
];

export const TRANSACTION_ROWS = [
  {
    id: 't1',
    titleKey: 'prizePayments.transactions.items.golden.title',
    idKey: 'prizePayments.transactions.items.golden.id',
    dateKey: 'prizePayments.transactions.items.golden.date',
    amountKey: 'prizePayments.transactions.items.golden.amount',
    status: 'success',
    amountTone: 'neutral',
    pendingStyle: false,
    icon: PRIZE_PAYMENTS_ASSETS.txnTrophy1,
    iconBg: 'bg-[rgba(255,221,184,0.3)]',
  },
  {
    id: 't2',
    titleKey: 'prizePayments.transactions.items.macro.title',
    idKey: 'prizePayments.transactions.items.macro.id',
    dateKey: 'prizePayments.transactions.items.macro.date',
    amountKey: 'prizePayments.transactions.items.macro.amount',
    status: 'success',
    amountTone: 'neutral',
    pendingStyle: false,
    icon: PRIZE_PAYMENTS_ASSETS.txnTrophy2,
    iconBg: 'bg-[rgba(233,221,255,0.3)]',
  },
  {
    id: 't3',
    titleKey: 'prizePayments.transactions.items.paypal.title',
    idKey: 'prizePayments.transactions.items.paypal.id',
    dateKey: 'prizePayments.transactions.items.paypal.date',
    amountKey: 'prizePayments.transactions.items.paypal.amount',
    status: 'completed',
    amountTone: 'debit',
    pendingStyle: false,
    icon: PRIZE_PAYMENTS_ASSETS.txnCard,
    iconBg: 'bg-[#dde2f3]',
  },
  {
    id: 't4',
    titleKey: 'prizePayments.transactions.items.wild.title',
    idKey: 'prizePayments.transactions.items.wild.id',
    dateKey: 'prizePayments.transactions.items.wild.date',
    amountKey: 'prizePayments.transactions.items.wild.amount',
    status: 'success',
    amountTone: 'neutral',
    pendingStyle: false,
    icon: PRIZE_PAYMENTS_ASSETS.txnTrophy3,
    iconBg: 'bg-[rgba(255,221,184,0.3)]',
  },
  {
    id: 't5',
    titleKey: 'prizePayments.transactions.items.urban.title',
    idKey: 'prizePayments.transactions.items.urban.id',
    dateKey: 'prizePayments.transactions.items.urban.date',
    amountKey: 'prizePayments.transactions.items.urban.amount',
    status: 'pending',
    amountTone: 'muted',
    pendingStyle: true,
    icon: PRIZE_PAYMENTS_ASSETS.txnPending,
    iconBg: 'bg-[rgba(227,227,222,0.3)]',
  },
];
